;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Movement.IsMoving",NewTagName="Movement.Status")
+GameplayTagRedirects=(OldTagName="Status.IsMoving",NewTagName="CharacterStatus.IsMoving")
+GameplayTagRedirects=(OldTagName="Status.StaminaRegen",NewTagName="CharacterStatus.StaminaRegen")
+GameplayTagRedirects=(OldTagName="Status",NewTagName="CharacterStatus")
+GameplayTagRedirects=(OldTagName="Abilities.Jump.JumpCostData",NewTagName="Abilities.Jump.JumpStaminaCost")
+GameplayTagList=(Tag="Abilities.Crouch",DevComment="")
+GameplayTagList=(Tag="Abilities.Jump",DevComment="")
+GameplayTagList=(Tag="Abilities.Jump.JumpStaminaCost",DevComment="")
+GameplayTagList=(Tag="Abilities.Sprint",DevComment="")
+GameplayTagList=(Tag="Abilities.Sprint.SpeedOverrideValue",DevComment="")
+GameplayTagList=(Tag="CharacterStatus.IsFalling",DevComment="")
+GameplayTagList=(Tag="CharacterStatus.IsMoving",DevComment="")
+GameplayTagList=(Tag="CharacterStatus.StaminaRegen",DevComment="")
+GameplayTagList=(Tag="GlobalEvents.Alarm",DevComment="")
+GameplayTagList=(Tag="NpcAI.SensorsUpdated",DevComment="")

