;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Movement.IsMoving",NewTagName="Movement.Status")
+GameplayTagRedirects=(OldTagName="Status.IsMoving",NewTagName="CharacterStatus.IsMoving")
+GameplayTagRedirects=(OldTagName="Status.StaminaRegen",NewTagName="CharacterStatus.StaminaRegen")
+GameplayTagRedirects=(OldTagName="Status",NewTagName="CharacterStatus")
+GameplayTagRedirects=(OldTagName="Abilities.Jump.JumpCostData",NewTagName="Abilities.Jump.JumpStaminaCost")
+GameplayTagRedirects=(OldTagName="Abilities.Crouch",NewTagName="Ability.Crouch")
+GameplayTagRedirects=(OldTagName="Abilities.Jump.JumpStaminaCost",NewTagName="Ability.Jump.JumpStaminaCost")
+GameplayTagRedirects=(OldTagName="Abilities.Jump",NewTagName="Ability.Jump")
+GameplayTagRedirects=(OldTagName="Abilities.Lockpick",NewTagName="Ability.Lockpick")
+GameplayTagRedirects=(OldTagName="Abilities.Sprint.SpeedOverrideValue",NewTagName="Ability.Sprint.SpeedOverrideValue")
+GameplayTagRedirects=(OldTagName="Abilities.Sprint",NewTagName="Ability.Sprint")
+GameplayTagRedirects=(OldTagName="Abilities",NewTagName="Ability")
+GameplayTagRedirects=(OldTagName="GlobalEvents.Alarm",NewTagName="Event.Alarm")
+GameplayTagRedirects=(OldTagName="GlobalEvents",NewTagName="Event")
+GameplayTagRedirects=(OldTagName="CharacterStatus.IsFalling",NewTagName="State.IsFalling")
+GameplayTagRedirects=(OldTagName="CharacterStatus.IsMoving",NewTagName="State.IsMoving")
+GameplayTagRedirects=(OldTagName="CharacterStatus.StaminaRegen",NewTagName="State.StaminaRegen")
+GameplayTagRedirects=(OldTagName="CharacterStatus",NewTagName="State")
+GameplayTagRedirects=(OldTagName="NpcAI.Guard.AlertThresholdMet",NewTagName="NPC.State.Alerted")
+GameplayTagRedirects=(OldTagName="NpcAI.Guard.Alerted",NewTagName="NPC.State.Alerted")
+GameplayTagRedirects=(OldTagName="NpcAI.Guard.PlayerLost",NewTagName="NPC.State.Search")
+GameplayTagRedirects=(OldTagName="NpcAI.Guard.SearchExpired",NewTagName="NPC.State.Unaware")
+GameplayTagRedirects=(OldTagName="NpcAI.Guard.SuspiciousActivityDetected",NewTagName="NPC.State.Suspicious")
+GameplayTagRedirects=(OldTagName="NpcAI.SensorsUpdated",NewTagName="NPC.Event.Investigate")
+GameplayTagRedirects=(OldTagName="NpcAI.States.EnterAlarmState",NewTagName="NPC.State.Combat")
+GameplayTagRedirects=(OldTagName="NpcAI.States.EnterSuspiciousState",NewTagName="NPC.State.Suspicious")
+GameplayTagList=(Tag="Ability.Crouch",DevComment="")
+GameplayTagList=(Tag="Ability.Jump.JumpStaminaCost",DevComment="")
+GameplayTagList=(Tag="Ability.Lockpick",DevComment="")
+GameplayTagList=(Tag="Ability.Slide",DevComment="")
+GameplayTagList=(Tag="Ability.Slide.JumpVelocityChange",DevComment="")
+GameplayTagList=(Tag="Ability.Sprint.SpeedOverrideValue",DevComment="")
+GameplayTagList=(Tag="Event.Alarm",DevComment="")

